[package]
name = "project_circuit"
type = "bin"
authors = [""]
compiler_version = ">=0.36.0"

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "merkle-trees-v0.0.1", directory = "packages/merkle-trees" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }